"""Account security customer sessions and recovery

Revision ID: 09f515516f7a
Revises: b3b9e15cbe9a
Create Date: 2026-10-06 18:17:31.445745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09f515516f7a'
down_revision = 'b3b9e15cbe9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_bucket',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('expires', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    with op.batch_alter_table('rate_bucket', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rate_bucket_expires'), ['expires'], unique=False)

    op.create_table('account_token',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('token_hash')
    )
    op.create_table('customer_session',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('kiosk_id', sa.Integer(), nullable=False),
    sa.Column('expires', sa.Float(), nullable=False),
    sa.Column('browser_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['kiosk_id'], ['kiosk.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('customer_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_session_expires'), ['expires'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_session_kiosk_id'), ['kiosk_id'], unique=False)

    op.create_table('job_review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['print_job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('print_job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('customer_session_id', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('pricing_version', sa.String(length=20), server_default='reference-v1', nullable=False))
        batch_op.create_unique_constraint('uq_print_job_customer_session', ['customer_session_id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disabled', sa.Boolean(), server_default=sa.false(), nullable=False))
        batch_op.add_column(sa.Column('session_version', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('totp_encrypted', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('totp_counter', sa.BigInteger(), server_default='-1', nullable=False))

    with op.batch_alter_table('user') as batch_op:
        batch_op.alter_column('disabled', existing_type=sa.Boolean(), server_default=None)
        batch_op.alter_column('session_version', existing_type=sa.Integer(), server_default=None)
        batch_op.alter_column('totp_counter', existing_type=sa.BigInteger(), server_default=None)
    with op.batch_alter_table('print_job') as batch_op:
        batch_op.alter_column('pricing_version', existing_type=sa.String(20), server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('totp_counter')
        batch_op.drop_column('totp_encrypted')
        batch_op.drop_column('session_version')
        batch_op.drop_column('disabled')

    with op.batch_alter_table('print_job', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint('uq_print_job_customer_session', type_='unique')
        batch_op.drop_column('pricing_version')
        batch_op.drop_column('customer_session_id')
        batch_op.drop_column('deleted_at')

    op.drop_table('job_review')
    with op.batch_alter_table('customer_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_session_kiosk_id'))
        batch_op.drop_index(batch_op.f('ix_customer_session_expires'))

    op.drop_table('customer_session')
    op.drop_table('account_token')
    with op.batch_alter_table('rate_bucket', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rate_bucket_expires'))

    op.drop_table('rate_bucket')
    # ### end Alembic commands ###
