"""Retry-safe device credential rotation

Revision ID: 5d8384a01701
Revises: 74b64d4324c1
Create Date: 2026-10-06 18:23:14.319842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d8384a01701'
down_revision = '74b64d4324c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kiosk', schema=None) as batch_op:
        batch_op.add_column(sa.Column('previous_device_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('previous_device_until', sa.Float(), nullable=True))
        batch_op.create_unique_constraint('uq_kiosk_previous_device_hash', ['previous_device_hash'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kiosk', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint('uq_kiosk_previous_device_hash', type_='unique')
        batch_op.drop_column('previous_device_until')
        batch_op.drop_column('previous_device_hash')

    # ### end Alembic commands ###
