"""Per-kiosk prices and immutable quote snapshots

Revision ID: a4d68bedf731
Revises: 5d8384a01701
Create Date: 2026-10-06 18:46:27.074637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4d68bedf731'
down_revision = '5d8384a01701'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kiosk', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prices', sa.JSON(), nullable=False, server_default='{}'))
        batch_op.add_column(sa.Column('configuration_version', sa.Integer(), nullable=False, server_default='1'))

    with op.batch_alter_table('print_job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quote_snapshot', sa.JSON(), nullable=True))

    prices={"bw_single":250,"bw_duplex":300,"color_single":1000,"color_duplex":1600,"art_single":4000,"art_duplex":7000}
    kiosk=sa.table('kiosk',sa.column('prices',sa.JSON()))
    op.get_bind().execute(kiosk.update().values(prices=prices))
    with op.batch_alter_table('kiosk') as batch_op:
        batch_op.alter_column('prices',existing_type=sa.JSON(),server_default=None)
        batch_op.alter_column('configuration_version',existing_type=sa.Integer(),server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('print_job', schema=None) as batch_op:
        batch_op.drop_column('quote_snapshot')

    with op.batch_alter_table('kiosk', schema=None) as batch_op:
        batch_op.drop_column('configuration_version')
        batch_op.drop_column('prices')

    # ### end Alembic commands ###
