"""Add isolated simulated print jobs

Revision ID: b3b9e15cbe9a
Revises: c9a8ae149169
Create Date: 2026-10-06 18:07:58.251874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3b9e15cbe9a'
down_revision = 'c9a8ae149169'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('print_job',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('kiosk_id', sa.Integer(), nullable=False),
    sa.Column('pages', sa.Integer(), nullable=False),
    sa.Column('amount_paise', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('duplex', sa.Boolean(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('claim_hash', sa.String(length=64), nullable=True),
    sa.Column('lease_until', sa.Float(), nullable=True),
    sa.CheckConstraint("state IN ('queued','claimed','printing','completed','needs_review')"),
    sa.CheckConstraint('amount_paise > 0'),
    sa.CheckConstraint('pages BETWEEN 1 AND 250'),
    sa.ForeignKeyConstraint(['kiosk_id'], ['kiosk.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('print_job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_print_job_kiosk_id'), ['kiosk_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_print_job_owner_id'), ['owner_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('print_job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_print_job_owner_id'))
        batch_op.drop_index(batch_op.f('ix_print_job_kiosk_id'))

    op.drop_table('print_job')
    # ### end Alembic commands ###
