"""Initial fleet identity schema

Revision ID: c9a8ae149169
Revises: 
Create Date: 2026-10-06 18:02:47.502664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9a8ae149169'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.Float(), nullable=False),
    sa.CheckConstraint("role IN ('admin','owner')"),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kiosk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('activation_hash', sa.String(length=64), nullable=True),
    sa.Column('activation_expires', sa.Float(), nullable=True),
    sa.Column('device_hash', sa.String(length=64), nullable=True),
    sa.Column('last_seen', sa.Float(), nullable=True),
    sa.Column('printer_status', sa.String(length=20), nullable=False),
    sa.Column('software_version', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activation_hash'),
    sa.UniqueConstraint('device_hash')
    )
    with op.batch_alter_table('kiosk', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kiosk_owner_id'), ['owner_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kiosk', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kiosk_owner_id'))

    op.drop_table('kiosk')
    op.drop_table('audit')
    op.drop_table('user')
    # ### end Alembic commands ###
